import React from 'react'
export const metadata = {
  title: "Contacts",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>contact</div>
  )
}

export default page