import React from "react";
import styles from "./blog.module.css";
import Link from "next/link";
import Image from "next/image";
export const metadata = {
  title: "Products",
  description: "Generated by create next app",
};
const getData = async () => {
  const response = await fetch("https://dummyjson.com/products");
  return response.json();
};

const page = async () => {
  const data = await getData();
  const products = data.products;
  return (
    <>
      <div className={styles.main_container}>
        {products.map((ele) => (
          <Link href={`/blog/${ele.id}`} className={styles.post} key={ele.id}>
            <div className={styles.link_container}>
              <Image
                className={styles.image}
                src={
                  ele.thumbnail
                }
                fill={true}
                alt="pic"
              />
            </div>
            <div className={styles.content}>
              <h1 className={styles.title}>{ele.title}</h1>
              <p className={styles.text}>{ele.description}</p>
            </div>
          </Link>
        ))}

     
      </div>
    </>
  );
};

export default page;
