import Navbar from "@/Components/Navbar/Navbar";
import "./globals.css";
import { Inter, Lalezar } from "next/font/google";
import Footer from "@/Components/Footer/Footer";
import ThemeProvider from "./context/themeContext";
const inter = Inter({ subsets: ["latin"] });
const lalezar = Lalezar({ subsets: ["arabic"], weight: "400" });

export const metadata = {
  title: "Hexa Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider>
        <div className="root_container">
          <Navbar />
          {children}
          <Footer />
        </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
