import React from 'react'
export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>portfolio</div>
  )
}

export default page